version: '3.7'

services:
  bootnode:
    hostname: bootnode
    build:
      dockerfile: bootnode/Dockerfile
      context: ..
    volumes:
      - bootstrap_data:/root/.ethereum
    command:
      --nodiscover
      --nat extip:${EXTERNAL_IP}
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"

volumes:
  bootstrap_data:
